# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

PBOTVM_SERIAL = ENV['PBOTVM_SERIAL'] || 5555
PBOTVM_HEALTH = ENV['PBOTVM_HEALTH'] || 5556
PBOTVM_DOMAIN = ENV['PBOTVM_DOMAIN'] || 'pbot-vm'

Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/testing64"
end

load '../common/Vagrantfile.common'
