apiVersion: apps/v1
kind: Deployment
metadata:
  name: candide-vm
  namespace: candide
  labels:
    app: candide-vm
spec:
  selector:
    matchLabels:
      app: candide-vm
  replicas: 2
  template:
    metadata:
      labels:
        app: candide-vm
    spec:
      containers:
        - name: candide-vm
          image: gcr.io/PROJECT_ID/REPOSITORY/IMAGE:GITHUB_SHA
          resources:
            requests:
              cpu: "0.1"
              memory: 100Mi
            limits:
              cpu: "0.1"
              memory: 100Mi
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: candide-vm
  namespace: candide
  labels:
    app: candide-vm
spec:
  selector:
    app: candide-vm
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
spec:
  podSelector:
    matchLabels:
      app: candide-vm
  policyTypes:
    - Egress
