#!/bin/sh

# File: tumbleweed
#
# Purpose: Provisioning script to install packages and set-up environment
# on OpenSUSE Tumbleweed for pbot-vm.

# SPDX-FileCopyrightText: 2024 Pragmatic Software <pragma78@gmail.com>
# SPDX-License-Identifier: MIT

# for virt-io socket
zypper -n in socat

# for `cc` C language support
zypper -n in libubsan1 libasan8 gdb gcc gcc-32bit glibc-32bit clang

# for `cc` additional languages
zypper -n in ksh zsh tcl lua php8-cli nodejs-common guile bff bc gcc-c++
zypper -n in --no-recommends clisp gcc-go java java-devel

# for pbot-vm guest-server support
zypper -n in perl-IPC-Run perl-JSON-XS

# disable networking
./guest/bin/network off nftables

echo 'Networking disabled.'
echo 'To re-enable, run ./guest/bin/network on nftables'
echo 'To disable again, run ./guest/bin/network off nftables'
