#!/bin/sh

# File: tumbleweed
#
# Purpose: Provisioning script to install packages and set-up environment
# on OpenSUSE Tumbleweed for pbot-vm.

# SPDX-FileCopyrightText: 2024 Pragmatic Software <pragma78@gmail.com>
# SPDX-License-Identifier: MIT

# for virt-io socket
zypper in socat

# for `cc` C language support
zypper in libubsan1 libasan8 gdb gcc-32bit glibc-32bit

# for pbot-vm guest-server support
zypper in perl-IPC-Run perl-JSON-XS make
cpan i IPC::Shareable

# for `cc` additional languages
zypper in ksh zsh tcl lua php8-cli nodejs-common guile bff bc gcc-c++
zypper in --no-recommends clisp gcc-go java java-devel
