#!/usr/bin/env perl

# File: pbot
#
# Purpose: PBot main entry point. See doc/QuickStart.md.

# SPDX-FileCopyrightText: 2021 Pragmatic Software <pragma78@gmail.com>
# SPDX-License-Identifier: MIT

use FindBin qw($RealBin);
use lib "$RealBin/../lib";
use lib "$ENV{HOME}/.pbot";

use PBot::PBot;

PBot::PBot->new(
    data_dir   => "$RealBin/../data",
    module_dir => "$RealBin/../modules",
    update_dir => "$RealBin/../updates",
)->start;
