#!/bin/sh

DOMAIN="${PBOTVM_DOMAIN:-pbot-vm}"
SERIAL="${PBOTVM_SERIAL:-5555}"
HEALTH="${PBOTVM_HEALTH:-5556}"

cat > serial-2.xml <<EOF
<serial type='tcp'>
    <source mode='bind' host='127.0.0.1' service='$SERIAL' tls='no'/>
    <protocol type='raw'/>
    <target port='2'/>
</serial>
EOF

cat > serial-3.xml <<EOF
<serial type='tcp'>
    <source mode='bind' host='127.0.0.1' service='$HEALTH' tls='no'/>
    <protocol type='raw'/>
    <target port='3'/>
</serial>
EOF

virsh attach-device --config $DOMAIN serial-2.xml
virsh attach-device --config $DOMAIN serial-3.xml

rm serial-[23].xml
